package db

// DefaultPermissions ...
var DefaultPermissions = map[string]PermissionLevel{
	"ping":        EveryoneLevel,
	"help":        UserLevel,
	"config":      OwnerLevel,
	"permissions": OwnerLevel,
	"app":         StaffLevel,
	"verify":      HelperLevel,
	"close":       HelperLevel,
	"deny":        HelperLevel,
	"logs":        HelperLevel,
	"userinfo":    UserLevel,
	"unverified":  StaffLevel,
	"level":       UserLevel,
	"levelcfg":    StaffLevel,
	"leaderboard": UserLevel,
	"restart":     HelperLevel,
	"invites":     StaffLevel,
	"open":        HelperLevel,
	"hello":       EveryoneLevel,
	"valid":       EveryoneLevel,
	"transcript":  StaffLevel,
	"remindme":    EveryoneLevel,
	"warn":        HelperLevel,
	"mute":        HelperLevel,
	"hardmute":    HelperLevel,
	"unmute":      HelperLevel,
	"kick":        StaffLevel,
	"ban":         StaffLevel,
	"unban":       StaffLevel,
	"modlogs":     HelperLevel,
}
